---
title: "Analysis Methods"
format: html
---

This is an introduction to the Analysis methods

## Detection of Birds
For this pilot study, we used Birdnet Analyzer v2.4 to batch analyze recordings based on location (32N, -117W). 
Detections were saved as csv, formatted for Raven selection tables.

::: callout-important
Note: All results are preliminary, data were not acoustically validated!
:::


Necessary Review:
- For each species, sort by confidence score (high to low) and review manually to determine species-specific confidence scores (see https://connormwood.com/wp-content/uploads/2024/02/wood-kahl-2024-guidelines-for-birdnet-scores.pdf)




::: callout- note
Note: Birdnet Analyzer was used on this pilot study for ease of use; however, Birdnet liscence limits its use. Funded studies will use an alternative (likely semi-custom) detector and classifier. Our intention is to rely on open source software for reproducible analyses. These pilot study data will be used to develop this classifier as time allows.
:::

## Detection of Bats


## Soundscape Analysis