---
title: "Future Research"
format: html
bibliography: references.bib
---

```{r futurePrep}
#| echo: false
#| include: false
library(here)
library(DT)
library(tidyverse)
library(dssd)
library(Distance)
here()

source(here::here("_code/_common.R"))


```
# Future of PAM research for Ridgeway's Rails and Southern California Wetland Habitats

Historical call-response surveys conducted since 1979 have provided a long time-series monitoring of breeding pairs of Ridgway's Rails in southern California. This survey design primarily relied on playback of duetting calls to elicit a response from local breeding pairs[@zembal2024]; however, specific field methods varied throughout the field season. Notably, [@thompson2024] noted that these playback methods work well when used sparingly. A recent statistical examination of call-response survey design recommended repeated sampling to decrease sampling bias[@stevens2024]. While historical call-response surveys have proven to be an effective approach to monitoring Ridgway's Rails, recent advances in PAM monitoring using acoustic recorders may provide a more standardized approach to monitoring Ridgeway's Rails populations that may ultimately lead to more robust estimation of population trends.

::: callout-importannt
## Management Needs will Define Role of PAM
Define Primary management needs, and identify secondary research questions that might be met by PAM
:::


## Pilot Study
This pilot study provides initial data to show a proof of concept and to collect preliminary data useful for developing a potential survey design. 

## Call-Response vs PAM
Even though both methods rely on using animal calls to detect the presence of Ridgway's rails, it is almost certain that these two methods would provide different population estimates. One is not inherently better than the other; they each have their strengths and limitations. 

| Call - Response |   | Passive Acoustics |
|------------------------------|-----------------|-------------------------|
| ✅High detection probability |  | ❌ Low detection rate |
| ❌ Potential impact on animals |  | ✅ Low/No disturbance |
| ❌ Increased sampling to reduce bias |  | ✅ Increased sampling to reduce bias |
| ❌ Animals may respond to increased sampling |  | ✅ No impact of increased sampling |
| ❌ Limited sampling to reduce habituation |  | ✅ Continuous monitoring |
| ✅ Immediate Results |  | ✅ Data permanence |
| ❌Observer bias in distance estimation |  | ✅ Multi-species monitoring |
| ❌ Limited scope (single species) |  | ✅ Better distance modeling |
|  |  | ❌ Big Data (!!) |
|  |  |  |

: Benefits and Limitations of Call-Response and PAM Sampling. ✅ identifies beneficial characteristics of sampling method, and ❌ identifies limitation of that sampling method.

In a perfect world, a 3-year study incorporating both methods would be conducted to make data-informed decisions. In reality this is rarely possible, and decisions must be made with imperfect data. Regardless, it is imperative that some sampling overlap be conducted in different habitats (or regions) to provide some level of 'validation' that will aid in interpreting the variation in results. 

## Survey Design
Acoustic distance sampling methods are well documented, and there are standard software platforms for survey design and data analysis. Still, we highly recommend proactive consultation with a distance sampling statistician prior to implementing a survey design (and ideally for the first set of analysis). 

## Methods
This pilot study used low-cost Audiomoth recorders. As with everything, there are trade-offs with different instruments. It may be that a higher quality recorder may provide a larger detection range or extended recording duration; a larger detection range may require fewer recorders total and an extended recording duration may require fewer field efforts to replace instruments. The total cost estimate should consider these ancillary costs. While consideration of a different recorder will require additional data collection to estimate the detection function, the Sweetwater Proving Pens make this an easy opportunity. 

Many bird species are vocal during the morning chorus and (less robustly) near sunset; many passive acoustic studies limit their recordings to these hours in order to extend their recording duration and reduce data sizes. Acoustic data is very rich data, with the potential to provide valuable information on other species of interest, potential impacts due to man-made noise, and other information about the environment. Increasingly, passive acoustics is being used to study insects, biodiversity, and habitat health. I strongly advise for some level of continuous recording in order to provide additional context about the ecosystem.

## Anthropogenic Impacts
Antropogenic noise was frequent in these recordings, and there is great potential for negative impacts on animals and the habitat. Noise may lead to masking of vocalizations (so that sounds cannot be detected over the noise), and animals may change their vocal behavior to accommodate increased noise levels.  High noise levels may also interfere with their ability to identify the presence of a predator or detect prey. Continous passive acoustic recordings, especially from different regions with different noise impacts, can provide sufficient data to identify changes in vocal behavior due to noise. 

## Biodiversity
Only a very small fraction of the acoustic data collected during this pilot study was examined. This data can be used to assess the potential for studying other bird species (such as threatened or invasive species, or the presence of predators) as well as bats and insects. Several high frequency recordings (192 kHz) are provided as part of this pilot study; these data can provide information related to the presence of bat species feeding in these habitats.

There are several Biodiversity Indices that may provide a means of assessing long term trends. 'Soundscape' levels are increasingly used to assess the level of noise within different frequency bands, and this can be a useful way to assess changes in the environment. 

## Open Science
Open science is a global movement to make scientific research and its outcomes freely accessible to everyone. It accelerates scientific progress and strengthens trust in research. This repository is publicly available, and the code and preliminary detection data are provided within this repository. I largely relied on open source software so that results are reproducible. I would recommend that future studies involving PAM extend the use of Open Science to include developing publicly available acoustic classifiers specific to this region, and considering the use of participatory science in data collection and analysis. 

