---
title: "todo"
format: html
---

### Next

-   [ ] Model Birdnet Performance Evaluation:
    -   [ ] Plot confidence scores (x) vs Frequency (n, on y axis)
    -   [ ] Random selection of clips from different confidence intervals
    -   [ ] Use Raven Review mode to review clips
-   [ ] Detection Review
    -   [ ] DD: measures incl. amplitude for all calls
    -   [ ] Eliminate false positives
    -   [ ] Identify false negatives
    -   [ ] Label Noise?
-   [ ] Start/End for each Recording
    -   Scan each recording for true START time and true END time

        -   For DD, only include data when both pen recordings were working

    -   Delete unneeded recordings (bad data)

    -   extract TRUE good data START and END times, add to deployDetails spreadsheet

    -   Once this data is revised, assess recording length in hours (in R deployTable.R)

    -   Determine if we need to revise data in bird_birdnet.Rmd? Or in other tables, figures?

    -   Start/End for each Recording

### Acoustic Indices

-   First, complete Start/End for each Recording
-   First, complete Detection Review

### Methods

-   [ ] Study Area- map buffer to default at slightly zoomed out, also decrease size of map
-   [ ] Recorders- Create prelim list of recorders, pros/cons, and links to comparative studies. Possibly put this in recommendations or in separate section re: recorders?
-   [ ] Analysis: Future: Need to validate recordings for specific species (Rails, at the least) and then calculate species-specific confidence thresholds using birdnetTools\<birdnet_calc_threshold.
-   [ ] Analysis: For each species, sort by confidence score (high to low) and review manually to determine species-specific confidence scores (see <https://connormwood.com/wp-content/uploads/2024/02/wood-kahl-2024-guidelines-for-birdnet-scores.pdf)>
-   [ ] Analysis: Then, Create a **wetland_bird_detectionTable** of species detected and add confidence intervals, order by confidence interval (high to low), and highlight endangered species (Rails, etc)
-   [ ] Analysis: Add Environmental Data (DRAFT complete for wind, rain... need to add temp?)
-   [ ] Detection Function: create test dataframe (from real data) with these columns: Distance, SightingID, GroupSize (always 2?), see [these](https://workshops.distancesampling.org/duke-spatial-2015/practicals/1-detection-functions-solutions.html) examples
-   [ ] Manual Review to assess classifier
    -   [ ] Review subset of data, determine if detection was true or false
    -   [ ] Create a plot of all manually reviewed detections where x axis is the confidence scores (from birdnet) and Y is Correct (true positives) or Wrong (false positives).
    -   [ ] What is the best threshold? Assess Precision & Recall and decide what is best for our study case.
    -   [ ] OR, model true detection as a function of model scores. (Do this above).

### Dashboard

-   [ ] do it!

### Results- Assessment

-   [ ] Review data to fix time series and ensure it is reasonable.

### Data

-   [ ] Map to satellite image
-   [ ] Add all photos from phone to images folder on desktop, add photonames to deployDetails/Location_Site table

### QAQC

-   [ ] Review recordings to find TRUE start/end time, add that to deployDetails, then create code to modify start/end time in datasets.
-   [ ] Remove any detections before or after recording start/end date/time
-   [ ] Check data for numeric, all caps, all lowercase, and other consistent formatting.
-   [ ] Create a Lat/Long check
-   [ ] Find length of deployment w/in bounds, same for recording deployment
-   [ ] Check if battery or storage limited recording?
-   [ ] QAQC for truncated recording or bad files, create a check for each recorder/storage card to ID possible problem cards/recorders
-   [ ] confirm that each deployment_ID is unique, and that the components of the deployment_ID match the appropriate column info
-   [ ] If a new upload, check to see if any previous entries are different than the current ones (to ID possible accidental modifications in the ODS file). Create a log of these.
-   [ ] Create a log of all the QAQC outputs with the date, etc.
-   [ ] Check for updates to the other sheets in the ODS workbook
-   [ ] Check that all files have recording percursor (missing on SPP-DD10_48c_20250716)
-   [ ] Add precursor to those files that are missing it
-   [ ] Check start time for all files to ensure it is UTC and 'correct' (close to other deployments)
-   [ ] Check for missing data
-   [ ] Acoustic recording start/end: Using Raven, find official start/end, and add to SE_DeployDetails, also, ID number of bad files
-   \[ \]

### Results

-   [ ] Intro: Scrolling Spectrogram, sample sounds

-   [ ] Summary Results:

-   [ ] DD: Warning note that further analysis is needed to fill out detection function, and that we need to do this for a wetland habitat (this is not typical habitat)

-   [ ] Link to Dashboard

-   [ ] Revise dielPlots to work for this data

### Dashboard

-   [ ] Value Boxes (Hrs Recording + Tb Data, \# Species Detected)
-   \[ \]

### Bibliography

### Biodiversity

### Bats

-   [ ] Review bat recordings to manually classify

-   [ ] Merge all detections for a recording

-   [ ] Modify *code/bat_kaleidoscope.r* file

    -   [ ] Remove any detections before or after recording start/end date/time

    -   [ ] Add columns for (1) Location, (2) Site

-   [ ] save as csv in github data folder

-   \[ \]

### 

## MoreInfo

[ObservableJS Video by Allison Horst](https://youtu.be/0srggostAko?feature=shared) 0.40.00

[R Graph Gallery– Amazing!](https://r-graph-gallery.com/interactive-charts.html)

[Birdnet w/ Raven Instructions](https://www.ravensoundsoftware.com/knowledge-base/acoustic-analysis-with-birdnet-and-almost-no-coding-practical-instructions/)

[Interactive Documents Github Pages+Quarto+Shiny](https://youtu.be/06H8k1nzZQ0?feature=shared) - great video

RStudio Trick: add ' ' to multi lines- You can use multi-line cursors by pressing alt + click + dragging down the cursor. If you're looking for more RStudio tricks, check out my video on that <https://www.youtube.com/watch?v=XHT1m-LKTVY&t=64s>

[Quarto Dashboards in 1 hr video by Mine](https://youtu.be/NoOU_nzeAGk?feature=shared)

[ggiraph for Interactive plots](https://allisonhorst.github.io/ggiraph-demo/demo.html)

[pamverse](https://nmfs-ost.github.io/PAMverse/content/AcousticDetections.html)

### Papers with reproducible figures/analyses

[Large-scale avian vocalization detection delivers reliable global biodiversity insights](https://www.pnas.org/doi/full/10.1073/pnas.2315933121)

[adiv: An r package to analyse biodiversity in ecology](https://besjournals.onlinelibrary.wiley.com/doi/10.1111/2041-210X.13430)

[BirdNET provides superior diversity estimates compared to observer-based surveys in long-term monitoring](https://www.sciencedirect.com/science/article/pii/S1470160X25006776)

### Papers for Future Studies

[Survey coverage, recording duration and community composition affect observed species richness in passive acoustic surveys](https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/2041-210X.13571)

[A post-processing framework for assessing BirdNET identification accuracy and community composition](https://onlinelibrary.wiley.com/doi/full/10.1111/ibi.13357)

[Advancing bird survey efforts through novel recorder technology and automated species identification](https://web.archive.org/web/20211203174336id_/https://nrm.dfg.ca.gov/FileHandler.ashx?DocumentID=193712&inline)

Analysis Methods

[Audiomoth Data Processing](https://github.com/ELBE223/audiomoth-data-processing/tree/main) (Diversity Analysis, PointCounts, etc)

[SoundscapeR Package w/ Vignette](https://thomasluypaert.github.io/soundscapeR_vignette/)

[Automatic detection for bioacoustic research: a practical guide from and for biologists and computer scientists](https://onlinelibrary.wiley.com/doi/pdf/10.1111/brv.13155)

## Notes

Terminal\
Ctrl-C to stop terminal

cd C:/Users/Shannon/Documents/Github/SECO-Pilot

quarto preview content/rails-results-new.qmd
