---
title: "_TestCode"
output: html_document
editor_options: 
  markdown: 
    wrap: 72
---

# Prep Code

```{r prep echo=FALSE include=FALSE}
library(here)
here()

source(here::here("_code/_common.R"))

```

```{r}
# Basic usage with defaults
result <- process_birdnet_data(dataset = "Appended", projectID = "rails2")

# Custom paths and timezone
result <- process_birdnet_data(
  dataset = "Appended", 
  projectID = "rails",
  raw_files_path = here("bigData/rails/rawBirdnetFiles"),
  output_path = here("output"),
  local_tz = "America/Los_Angeles"
)


```

```{r}
new <- readRDS(here("data/birdnet_Rails_TJE.rds"))
old <-readRDS(here("data/birdnet_rails.rds"))
newer <- readRDS(here("data/birdnet_rails2_Appended.rds"))

# Filter the 'old' dataframe to only keep rows where site == "TJE"
old_filtered <- old %>%
  filter(location == "TJE")

# Check if 'new' and 'old_filtered' are identical
are_identical <- all.equal(newer, old, check.attributes = FALSE)

if (isTRUE(are_identical)) {
  print("The dataframes are identical.")
} else {
  print("The dataframes are NOT identical.")
  print(are_identical)  # This will show you the differences
}

# identical(new, old)
```


```{r convert}
myBirdnetFile <- "E:/Rails/recordings/TJE-01/TJE-01_48c_20250515/birdnetLocal_TJE-01_48c_20250515/BirdNET_SelectionTable_TJE-01_48c_20250515.txt"

convert_birdnet_to_raven(
  infile = myBirdnetFile
)

#Then review using selection window, see section 4.2 in file:///C:/Users/Shannon/Raven%20Pro%201.6/Documentation/Raven14UsersManual.pdf or http://zenodo.org/records/8415090/files/BirdNET%20Guide%20V%201.0%20-%202024-08-05.pdf

```