---
title: "bird_birdnet2"
output: html_document
editor_options: 
  markdown: 
    wrap: 72
---

# Prep Code

```{r prep echo=TRUE include=FALSE}
library(here)
here()

source(here::here("_code/_common.R"))
```



# Create data subsets for analysis and save as csv (to read in by PAMverse)

*Ideally, pamverse could accept an rds file, talk with Taiki about this*

```{r data-subsets}
#top 10 species
birdnet_top10 <- birdnet_all %>% 
  count(Common.Name, sort = TRUE) %>% # Count #detections per species 
  slice_head(n = 10) %>% # Get top 10 species
  left_join(birdnet_all, by = "Common.Name") # join back to original data
write_csv(birdnet_top10, here("bigData", "birdnet_top10.csv"))

#top 10 species- TJE
birdnet_top10_TJE <- birdnet_all %>% 
  filter(Location == "TJE") %>%
  count(Common.Name, sort = TRUE) %>% # Count #detections per species 
  slice_head(n = 10) %>% # Get top 10 species
  left_join(birdnet_all, by = "Common.Name") # join back to original data
write_csv(birdnet_top10_TJE, here("bigData", "birdnet_top10_TJE.csv"))
  

#top 10 species- SCI
birdnet_top10_SCI <- birdnet_all %>% 
  filter(Location == "SCI") %>%
  count(common_name, sort = TRUE) %>% # Count #detections per species 
  slice_head(n = 10) %>% # Get top 10 species
  left_join(birdnet_all, by = "common_name") # join back to original data
write_csv(birdnet_top10_SCI, here("bigData", "birdnet_top10_SCI.csv"))


#Ridgeway's Rails
birdnet_LFRR <- birdnet_All %>% dplyr::filter(common_name == "Ridgway's Rail")
write_csv(birdnet_LFRR, here("bigData", "birdnet_LFRR.csv"))
saveRDS(birdnet_LFRR, file=here("data", "birdnet_LFRR.rds"))

# Ridgeway's Rails for Detection Distance
birdnet_LFRR_DD <- birdnet_LFRR %>% filter(!location == "TJE") %>%
  filter(!location == "SGR")%>%
  filter(!site == "1N") %>%
  filter(!site == "3S")
write_csv(birdnet_LFRR_DD, here("bigData", "birdnet_LFRR_DD.csv"))
write_delim(birdnet_LFRR_DD, here("bigData", "birdnet_LFRR_DD.txt"), delim = "\t" )


#by Location
birdnet_TJE <- filter(birdnet_all, location == "TJE")
write_csv(birdnet_TJE, here("bigData", "birdnet_TJE.csv"))

birdnet_SCI <- filter(birdnet_all, location == "SCI")
write_csv(birdnet_SCI, here("bigData", "birdnet_SCI.csv"))

birdnet_SPP <- filter(birdnet_all, location == c("SPP", "SGR"))
write_csv(birdnet_SPP, here("bigData", "birdnet_SPP.csv"))

#Priority Species
#Consider top 10 and one or more these species:
  #Bell's Sparrow, Beldings Savannah Sparrow, California Least Tern, western Snowy Plover, 
  #California Gnatcatcher, Least Bell's Vireo 
priority <- birdnet_TJE %>%
  count(Common.Name, sort = TRUE) %>% 
  slice_head(n = 10) %>%
  pull(Common.Name) %>% 
  union("Bell's Vireo") 

priority <- birdnet_TJE %>%
  filter(Common.Name %in% priority)


```

# PAMverse Plots

```{r birdnet-pamPlots}
# identify dataset
myData <- here("bigData", "birdnet_SPP_LFRR.csv")

#interactive shiny detection explorer (if needed)
#runDetectionExplorer(myData)

loadDetectionData(x=myData, source='csv', detectionType='detection', wide=FALSE, tz='UTC',
                  columnMap=list(UTC='datetime_UTC', species='Common.Name', Latitude='latitude',
                  Longitude='longitude'))

plotAcousticScene(x=myData, combineYears=FALSE) 

plotPolarDetections(x=myData, group='species', facet='species', bin='detection/hour', quantity='count')

plotDetectionBoxplot(x=myData, group='species', facet='species', bin='hour/day', combineYears=FALSE)

```
