project:
  type: book
  output-dir: _book
bibliography: references.bib

book:
  title: "Ridgway's Rail Passive Acoustic Monitoring"
  subtitle: "A manager's report for designing future scientific studies"
  author: "Shannon Rankin: Sound Ecology Pilot Studies"
  date: last-modified
  repo-url: https://github.com/shannonrankin/SECO-Pilot
  repo-actions: [source, issue]
  downloads: [pdf]
  chapters:
    - index.qmd
    - 01-intro.qmd
    - 02-methods.qmd
    - 03-rails-summary.qmd
    - 04-rails-assessment.qmd
    - 05-rails-biodiversity.qmd
    - 06-rails-insects.qmd
    - 07-rails-future.qmd



format:
  html:
    theme: cosmo
    toc: true
    number-sections: true
    link-external-newwindow: true
  pdf:
    documentclass: scrreprt
    toc: true
    number-sections: true
